### PR TITLE
Add support for tags

### PR DESCRIPTION
**Pull request by nachomdo**
This PR is intended to extend the functionality of the NoticeReporter interface to support tags.

image

### CODE REVIEW

**Comment by sgerrand** [comment]
👋 @joshuap @starrhorne: Would you please review these changes. We'd like to use more of the features available in Honeybadger's API via the Java client.

**Comment by joshuap** [comment]
Sorry for the delay. I think this is looking good. A few things:

The build is failing on Travis because (I think) the latest container image doesn't support JDK 7. You should be able to get oraclejdk7 and oraclejdk8 builds passing by pulling in this commit:

https://github.com/honeybadger-io/honeybadger-java/commit/0ffc680017f19460fdbfa668905e9599d51e035e

The openjdk7 build will still fail, however, and I'm not sure why. Any ideas? See here:

https://travis-ci.org/honeybadger-io/honeybadger-java/builds/383374481

Beyond that, could you update this PR to add a usage example to README.md, @nachomdo? Thanks!

Also looping in @dekobon and his folks in case they have any comments on this.

**Comment by dekobon** [comment]
For what it is worth, the honeybadger-io 2.0 work that I was in the middle of supported tags: https://github.com/honeybadger-io/honeybadger-java/compare/master...dekobon:2.0.0#diff-21789fb0ba1caccd1e427ef1c1ccf036R132

I had my work situation suddenly change and I wasn't able to merge the work. I believe it is done. However, I have a concern about it not reporting the environment correctly all of the time based on a sample application that I was working on.

I believe this is a more robust set of changes that moves Honeybadger forward. If anyone would like to adopt it and move it the last 5% forward, it would be much appreciated.

**Comment by JasonTrue** [comment]
@nachomdo the 2.0.0 branch should be a bit closer to release-ready. If you've got a moment can you grab it and see if the tags support there works for you?

I may put together a solution to allow hooks in the existing error handlers to avoid the need for a custom implementation (instead of manually invoking reportError) but haven't quite gotten there yet.

**Comment by joshuap** [comment]
I'm going to close this PR--let's continue discussion of the new tags support on #56!

**Pull request closed without merging**
