### PR TITLE
Deploy with GitHub actions

### LINKED ISSUE #440: Automate releases using Github Actions

### PR DESCRIPTION
**Pull request by subzero10**
Closes #440.
An attempt to simplify the release process, as defined in `RELEASING.md`.

## TODO:

- [x] Create Github workflow
- [x] Import GPG private key
- [x] Execute maven build
- [x] Supply release version from Github actions inputs
- [x] Update `RELEASING.md`
- [x] Merge this PR and deploy
- [ ] Verify deployment on an example project

### CODE REVIEW

**Comment by subzero10** [comment]
I'm not familiar with all this process, so there's a lot of trial and error going on.
Nevertheless, I am getting close:
- [x] Create a gpg key
- [x] Import gpg key for github workflow using setup-java action
- [x] `mvn release-clean release-prepare`
- [ ] `mvn release-perform`
- [ ] `git push` tags
- [ ] Promote build on oss.sonatype.org # I think this will remain a manual step

**Comment by subzero10** [comment]
For the moment, I am blocked because I don't have permissions to verify and promote builds on `oss.sonatype.org`. I have created this [JIRA ticket](https://issues.sonatype.org/browse/OSSRH-88484).

Poking @joshuap, as you may have to verify the fact that I am a contributor :)

**Comment by joshuap** [comment]
> For the moment, I am blocked because I don't have permissions to verify and promote builds on `oss.sonatype.org`. I have created this [JIRA ticket](https://issues.sonatype.org/browse/OSSRH-88484).
> 
> Poking @joshuap, as you may have to verify the fact that I am a contributor :)

done!

**Comment by subzero10** [comment]
Done! `2.1.2` was deployed using Github Actions!
image

**Pull request merged**
